### ISSUE TITLE
Frames of varying length

### ISSUE THREAD

**Issue by abhiray92** [HHTseng/video-classification#38]
HI @HHTseng , the CRNN model is working fine for me, however, the videos in my dataset has varying frame length, I believe you already have the code for this issue as discussed in the link below . Can you please share the code for the same?

https://github.com/HHTseng/video-classification/issues/5

**Comment by abhiray92** [comment]
Hi @HHTseng can you please share the code for varying frame length? Its very important. Thanks

**Comment by HHTseng** [comment]
yes I had it sometime before, allow me to take a few days to find it

**Comment by abhiray92** [comment]
@HHTseng Thanks alot! That would really be very helpful. 
Thanks

**Comment by abhiray92** [comment]
Hi @HHTseng Did you get a chance to check for the code?
Thanks

**Comment by abhiray92** [comment]
Hi @HHTseng Did you get a chance to check for the code?
Thanks

**Comment by HHTseng** [comment]
Please check out the files in the folder **ResNetCRNN_varylength** and run _UCF101_ResNetCRNN_varlen.py_. This necessarily takes longer time to load and run. Let me know if there's any bug spotted, thanks!

**Comment by abhiray92** [comment]
@HHTseng Thanks a MILLION! I will update you as soon as I check and run the code.

**Comment by abhiray92** [comment]
I got the below error after running the code - 
PS: I have made a few changes to run the model on grayscale images. The mean and std for the transforms parameter has been set to mean=[0.5], std=[0.225].
```
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\abhir\.conda\envs\torch\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\abhir\.conda\envs\torch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\abhir\.conda\envs\torch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Theses\video-classification\ResNetCRNN_varylength\functions.py", line 51, in __getitem__
    channels = len(self.transform.__dict__['transforms'][2].__dict__['mean'])  # get number of channels from Transformation
KeyError: 'mean'
```

**Comment by abhiray92** [comment]
@HHTseng I am constantly getting this error - 

```
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\abhir\.conda\envs\torch\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\abhir\.conda\envs\torch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\abhir\.conda\envs\torch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Theses\video-classification\CRNN\functions.py", line 51, in __getitem__
    channels = len(self.transform.__dict__['transforms'][2].__dict__['mean'])  # get number of channels from Transformation
KeyError: 'mean'
```

**Comment by berna-ylmz** [comment]
Did you solve this problem @abhiray92  ?

**Comment by abhiray92** [comment]
@Berna-lab Yes, this problem has been resolved. The code has already been uploaded on the repository.
Thanks

**Comment by abhiray92** [comment]
@Berna-lab Yes, my images were in grayscale, so I just set the value of 'Channel = 1'. And it worked.

**Comment by berna-ylmz** [comment]
Thanks @abhiray92
